### ISSUE TITLE
ft01_poisson.py problem

### ISSUE THREAD

**Issue by gtelzur** [hplgit/fenics-tutorial#39]
I am trying to execute ft01_poisson.py and I get the following error:

fenics> python ./ft01_poisson.py 
Traceback (most recent call last):
  File "./ft01_poisson.py", line 11, in <module>
    from fenics import *
  File "/usr/lib/python2.7/dist-packages/fenics/__init__.py", line 7, in <module>
    from dolfin import *
  File "/usr/lib/python2.7/dist-packages/dolfin/__init__.py", line 17, in <module>
    from . import cpp
  File "/usr/lib/python2.7/dist-packages/dolfin/cpp/__init__.py", line 43, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/dolfin/cpp/common.py", line 32, in <module>
    _common = swig_import_helper()
  File "/usr/lib/python2.7/dist-packages/dolfin/cpp/common.py", line 28, in swig_import_helper
    _mod = imp.load_module('_common', fp, pathname, description)
ImportError: /usr/lib/x86_64-linux-gnu/libhwloc.so.5: symbol migrate_pages, version libnuma_1.2 not defined in file libnuma.so.1 with link time reference

I am using a Linux mint 18.2 Sonya, 64-bit laptop, kernel  4.13.5-041305-generic

Regards,

Guy

**Comment by alogg** [comment]
I have no idea why you get this error, but it is not related to the tutorial (only to your particular FEniCS installation) so I'm closing this issue. Thanks for reporting.
